### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by Vlad1mir-D** [vikulin/ed25519-gpu-vanity#1]
How could code in this repo be licensed under GPL-3 when it is [licensed under Apache License 2.0](https://github.com/solana-labs/solana-perf-libs/blob/master/LICENSE) and you don't own the code?

**Comment by vikulin** [comment]
GPL license is applicable for individual files where my modifications were made. Other files are still covered Apache license and it doesn't contract GPL since no dedicated license was appended for each file.
